name: jexpoints
description: Loyalty project for Jexbit

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.0
  json_annotation: any
  cupertino_icons: ^1.0.2
  shared_preferences: any
  pin_code_fields: ^7.4.0
  auth_buttons: ^2.0.4
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  google_sign_in: ^5.3.0
  flutter_facebook_auth: ^4.3.0
  sign_in_with_apple: ^4.0.0
  # flutter_barcode_scanner: ^2.0.0
  card_swiper: ^2.0.1
  percent_indicator: ^4.0.0
  carousel_slider: ^4.1.1
  qr_flutter: ^4.0.0
  circular_countdown_timer: ^0.2.1
  flutter_map: ^0.14.0
  google_maps_flutter: ^2.1.5
  provider: ^6.0.2
  hidden_drawer_menu: ^3.0.1
  flutter_zoom_drawer: ^3.0.2
  lottie: ^1.3.0
  animated_splash_screen: ^1.2.0
  local_auth: ^2.1.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  json_serializable: any
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
